### PR TITLE
Apply discount to a charge

### PR DESCRIPTION
**Pull request by patrikniebur**
Added total discount calculation to be applied on line items. 
I tried displaying this as another line item but in stripe they are not allowed to have negative amounts. 

Better way would be to use stripe coupons but for simplicity this is what I'm going to use now so I thought I would share in the PR

Also added metadata to keep track if voucher has been used.

### CODE REVIEW

**Comment by st8st8** [comment]
OK - thanks.... 

Have you considered using get_price_breakdown to work out the discounted line price?

https://django-oscar.readthedocs.io/en/3.1/ref/apps/basket.html#oscar.apps.basket.abstract_models.AbstractLine.get_price_breakdown

I might be more robust than splitting the discount across the lines if it can be made to work....

**Comment by patrikniebur** [comment]
Updated to use `get_price_breakdown()` as you suggested, it's a lot better thanks!

Word of caution - there's unresolved bug with offers in oscar https://github.com/django-oscar/django-oscar/issues/3685
You need to set `OSCAR_OFFERS_INCL_TAX = True` for it to work correctly. 
Otherwise it displays different calculation in checkout then what it returns from `get_price_breakdown`

**Comment by patrikniebur** [comment]
Hey @st8st8 any thoughts on the above? Just want to know if I should use fork of the package or this can be added into the release. Thanks!

**Comment by st8st8** [comment]
I didn’t get notified that you’d made this change. I’m away just now, so it will be a week or so before u can take a proper look…Thanks for the updateSteve Bradshaw.On 5 Sep 2024, at 18:20, Patrik Niebur ***@***.***> wrote:﻿
Hey @st8st8 any thoughts on the above? Just want to know if I should use fork of the package or this can be added into the release. Thanks!

**Comment by patrikniebur** [comment]
Hey @st8st8 sorry to bug you about this again. Can you give me an update please? No worries if you are busy just so I know what to expect.
Thanks

**Comment by st8st8** [comment]
Sorry - lost track a bit.  I'll get this merged and released for you....

**Comment by st8st8** [comment]
v0.8 has been released to pypi....

**Comment by patrikniebur** [comment]
Awesome, thank you!

**Pull request merged**
